# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/baffinvektt/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/samsung/baffinvektt

PRODUCT_COPY_FILES += \
    vendor/samsung/baffinvektt/proprietary/vendor/bin/cbd:$(TARGET_COPY_OUT_VENDOR)/bin/cbd \
    vendor/samsung/baffinvektt/proprietary/vendor/firmware/bcm4334.hcd:$(TARGET_COPY_OUT_VENDOR)/firmware/bcm4334.hcd \
    vendor/samsung/baffinvektt/proprietary/vendor/firmware/bcm4334_murata.hcd:$(TARGET_COPY_OUT_VENDOR)/firmware/bcm4334_murata.hcd \
    vendor/samsung/baffinvektt/proprietary/vendor/firmware/bcm4334_semco.hcd:$(TARGET_COPY_OUT_VENDOR)/firmware/bcm4334_semco.hcd \
    vendor/samsung/baffinvektt/proprietary/vendor/bin/gpsd:$(TARGET_COPY_OUT_VENDOR)/bin/gpsd \
    vendor/samsung/baffinvektt/proprietary/vendor/etc/gps.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gps.xml \
    vendor/samsung/baffinvektt/proprietary/vendor/etc/wifi/bcmdhd_apsta.bin_b2:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/bcmdhd_apsta.bin_b2 \
    vendor/samsung/baffinvektt/proprietary/vendor/etc/wifi/bcmdhd_mfg.bin_b2:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/bcmdhd_mfg.bin_b2 \
    vendor/samsung/baffinvektt/proprietary/vendor/etc/wifi/bcmdhd_p2p.bin_b2:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/bcmdhd_p2p.bin_b2 \
    vendor/samsung/baffinvektt/proprietary/vendor/etc/wifi/bcmdhd_sta.bin_b2:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/bcmdhd_sta.bin_b2 \
    vendor/samsung/baffinvektt/proprietary/vendor/etc/wifi/default_ap.conf:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/default_ap.conf \
    vendor/samsung/baffinvektt/proprietary/vendor/etc/wifi/nvram_mfg.txt:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/nvram_mfg.txt \
    vendor/samsung/baffinvektt/proprietary/vendor/etc/wifi/nvram_mfg.txt_murata:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/nvram_mfg.txt_murata \
    vendor/samsung/baffinvektt/proprietary/vendor/etc/wifi/nvram_mfg.txt_murata_b2:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/nvram_mfg.txt_murata_b2 \
    vendor/samsung/baffinvektt/proprietary/vendor/etc/wifi/nvram_mfg.txt_semcosh:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/nvram_mfg.txt_semcosh \
    vendor/samsung/baffinvektt/proprietary/vendor/etc/wifi/nvram_net.txt:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/nvram_net.txt \
    vendor/samsung/baffinvektt/proprietary/vendor/etc/wifi/nvram_net.txt_murata:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/nvram_net.txt_murata \
    vendor/samsung/baffinvektt/proprietary/vendor/etc/wifi/nvram_net.txt_murata_b2:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/nvram_net.txt_murata_b2 \
    vendor/samsung/baffinvektt/proprietary/vendor/etc/wifi/nvram_net.txt_semcosh:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/nvram_net.txt_semcosh \
    vendor/samsung/baffinvektt/proprietary/vendor/lib/egl/egl.cfg:$(TARGET_COPY_OUT_VENDOR)/lib/egl/egl.cfg \
    vendor/samsung/baffinvektt/proprietary/vendor/lib/egl/libEGL_mali.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libEGL_mali.so \
    vendor/samsung/baffinvektt/proprietary/vendor/lib/egl/libGLESv1_CM_mali.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libGLESv1_CM_mali.so \
    vendor/samsung/baffinvektt/proprietary/vendor/lib/egl/libGLESv2_mali.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libGLESv2_mali.so \
    vendor/samsung/baffinvektt/proprietary/vendor/lib/hw/audio.primary.smdk4x12.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/audio.primary.smdk4x12.so \
    vendor/samsung/baffinvektt/proprietary/vendor/lib/hw/camera.smdk4x12.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/camera.smdk4x12.so \
    vendor/samsung/baffinvektt/proprietary/vendor/lib/hw/gps.exynos4.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/gps.exynos4.so \
    vendor/samsung/baffinvektt/proprietary/vendor/lib/libETC1.so:$(TARGET_COPY_OUT_VENDOR)/lib/libETC1.so \
    vendor/samsung/baffinvektt/proprietary/vendor/lib/libMali.so:$(TARGET_COPY_OUT_VENDOR)/lib/libMali.so \
    vendor/samsung/baffinvektt/proprietary/vendor/lib/libUMP.so:$(TARGET_COPY_OUT_VENDOR)/lib/libUMP.so \
    vendor/samsung/baffinvektt/proprietary/vendor/lib/lib_SamsungRec_V02002.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib_SamsungRec_V02002.so \
    vendor/samsung/baffinvektt/proprietary/vendor/lib/lib_Samsung_Resampler.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib_Samsung_Resampler.so \
    vendor/samsung/baffinvektt/proprietary/vendor/lib/lib_Samsung_SB_AM_for_ICS_v03007.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib_Samsung_SB_AM_for_ICS_v03007.so \
    vendor/samsung/baffinvektt/proprietary/vendor/lib/libakm.so:$(TARGET_COPY_OUT_VENDOR)/lib/libakm.so \
    vendor/samsung/baffinvektt/proprietary/vendor/lib/libaudio-ril.so:$(TARGET_COPY_OUT_VENDOR)/lib/libaudio-ril.so \
    vendor/samsung/baffinvektt/proprietary/vendor/lib/libfactoryutil.so:$(TARGET_COPY_OUT_VENDOR)/lib/libfactoryutil.so \
    vendor/samsung/baffinvektt/proprietary/vendor/lib/libomission_avoidance.so:$(TARGET_COPY_OUT_VENDOR)/lib/libomission_avoidance.so \
    vendor/samsung/baffinvektt/proprietary/vendor/lib/libsamsungDiamondVoice.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsamsungDiamondVoice.so \
    vendor/samsung/baffinvektt/proprietary/vendor/lib/libsamsungRecord.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsamsungRecord.so \
    vendor/samsung/baffinvektt/proprietary/vendor/lib/libsamsungSoundbooster.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsamsungSoundbooster.so \
    vendor/samsung/baffinvektt/proprietary/vendor/lib/libsec-ril.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsec-ril.so \
    vendor/samsung/baffinvektt/proprietary/vendor/lib/libsecnativefeature.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsecnativefeature.so \
    vendor/samsung/baffinvektt/proprietary/vendor/lib/libsecril-client.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsecril-client.so \
    vendor/samsung/baffinvektt/proprietary/vendor/lib/libstlport.so:$(TARGET_COPY_OUT_VENDOR)/lib/libstlport.so \
    vendor/samsung/baffinvektt/proprietary/vendor/lib/libvdis.so:$(TARGET_COPY_OUT_VENDOR)/lib/libvdis.so \
    vendor/samsung/baffinvektt/proprietary/vendor/firmware/fimc_is_fw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/fimc_is_fw.bin \
    vendor/samsung/baffinvektt/proprietary/vendor/firmware/libpn544_fw.so:$(TARGET_COPY_OUT_VENDOR)/firmware/libpn544_fw.so \
    vendor/samsung/baffinvektt/proprietary/vendor/firmware/mfc_fw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mfc_fw.bin \
    vendor/samsung/baffinvektt/proprietary/vendor/firmware/setfile.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/setfile.bin
